#!/bin/sh
# Usage: ncgetty [-s] N [additional arguments for nclogin]
if [ "$1" = '-s' ]
then
  sw=s
  shift
else
  sw=
fi
vt="$1"
shift
/bin/chmod 0620 /dev/tty$vt
/bin/chown root:tty /dev/tty$vt
exec /bin/openvt -c "$vt" -fe$sw -- /usr/sbin/nclogin -t linux -L en_US.UTF-8 -Wu "$@"
