#!/bin/bash

readonly syslog=user.info

fatal() {
  echo "$*"
  sleep 5
  exit 1
} >&2

if [ "${1:0:1}" == ':' ]
then
  display="$1"
  exec 2> >(exec /bin/logger -p "$syslog" -t "nclxorg[$$]" -s)

  [[ "${CTTY:=$(/bin/ps -o tty= $$)}" =~ ^tty([1-9][0-9]?)$ ]] || \
    fatal "Cannot determine virtual terminal name for '$CTTY'"
  printf -v console 'vt%02u' "${BASH_REMATCH[1]}"; unset CTTY

  mcookie="$(/usr/bin/mcookie)" && test -n "$mcookie" || \
    fatal "Failed to generate magic cookie for xauth"

  serverauth="/var/run/xorg.auth.$$"
  trap '/bin/rm -f "$serverauth"' EXIT
  test -e "$serverauth" || > "$serverauth"

  [[ "$display" =~ ^:[0-9]+$ ]] || fatal "Invalid display: '$display'"
  /usr/bin/xauth -q -f "$serverauth" add "$display" . "$mcookie"
  /usr/bin/setfacl -b -m "u:$USER:r" "$serverauth"

  test -d /tmp/.X11-unix || /bin/mkdir -m 1777 /tmp/.X11-unix

  printf -v command ' %q' "$0" -- \
    "$mcookie" "$display" "$console" -auth "$serverauth" "${@:2}"
  exec /bin/busybox su -c \
    "${command:1}" -l -s /bin/bash "$USER" >&2 < /dev/null
elif [ $# -ge 6 -a "$1" == '--' -a "${3:0:1}" == ':' ]
then
  readonly mcookie="$2" display="$3"
  clientauth="${XAUTHORITY:-$HOME/.Xauthority}"
  test -e "$clientauth" || /usr/bin/touch "$clientauth"
  /usr/bin/xauth -q add "$display" . "$mcookie"

  exec &> >(exec /bin/logger -p "$syslog" -t "xorg[$$]" &> /dev/null)
  exec /usr/bin/xinit -- /usr/bin/X "${@:3}"
else
  fatal "Unrecognized invocation context:" "$0" "$@"
fi
